- name: Template /etc/netplan/config.yaml
  ansible.builtin.template:
    src: 50-static-ip.yaml.j2
    dest: "{{dest_file}}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: apply netplan