- name: Template netplan config.yaml
  ansible.builtin.template:
    src: "{{source_template}}.j2"
    dest: "{{dest_file}}"
    mode: '0600'
  become: true
  notify: apply netplan

- name: Fix permissions
  ansible.builtin.file:
    path: /etc/netplan
    owner: root
    group: root
    mode: '0600'
    recurse: yes
  become: true

# https://unix.stackexchange.com/questions/681220/netplan-generate-gateway4-has-been-deprecated-use-default-routes-instead