- name: Template netplan config.yaml
  ansible.builtin.template:
    src: "{{source_template}}.j2"
    dest: "{{dest_file}}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: apply netplan